// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231110213331_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactId");

                    b.HasIndex("MobilePhone")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = new Guid("42da56f3-47b2-400b-b41a-f0f048ecbe58"),
                            BirthDate = new DateTime(1982, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Programmer",
                            MobilePhone = "+375291234569",
                            Name = "Luke"
                        },
                        new
                        {
                            ContactId = new Guid("77cd0cec-b448-45c1-a805-07f9ed5297da"),
                            BirthDate = new DateTime(1993, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Accountant",
                            MobilePhone = "+375331238669",
                            Name = "Madeleine"
                        },
                        new
                        {
                            ContactId = new Guid("2490fb81-134b-4cec-bf99-39032aa77dc5"),
                            BirthDate = new DateTime(2002, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Programmer",
                            MobilePhone = "+375298732839",
                            Name = "Ilya"
                        },
                        new
                        {
                            ContactId = new Guid("b8c52266-5927-493e-8630-bdf10e54240d"),
                            BirthDate = new DateTime(2000, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Loader",
                            MobilePhone = "+375441254889",
                            Name = "Oswald"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
